### \u5F00\u53D1\u73AF\u5883\uFF0C\u4E0D\u6CE8\u518C\u5230nacos\uFF0C\u65B9\u4FBF\u8C03\u8BD5
spring.cloud.service-registry.auto-registration.enabled=false
spring.cloud.discovery.client.simple.instances.service-system[0].uri=http://127.0.0.1:7710
spring.cloud.discovery.client.simple.instances.service-user[0].uri=http://127.0.0.1:7720
spring.cloud.discovery.client.simple.instances.service-course[0].uri=http://127.0.0.1:7730
